image:
  registry: registry.gitlab.com
  image: gitlab-org/gitlab-runner
  tag: alpine-v15.3.3
imagePullPolicy: Always
gitlabUrl: "https://gitlab.com/"
runnerRegistrationToken: "GR1348941RtLRvj4h1j-YXTB_YQyw"
unregisterRunners: true
rbac:
  create: true
  clusterWideAccess: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]
metrics:
  enabled: true
runners:
  privileged: true
