grafana:
  aditionalDatasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      maxLines: 1000
        # https://github.com/DevOps-Corner/loki/blob/master/datasource.yaml
